### ISSUE TITLE
What is this for?

### ISSUE THREAD

**Issue by chessai** [andrewthad/type-containers#1]
Map for TypeRep? What do you intend to use this for?

**Comment by chessai** [comment]
also, I think the Map newtype can be useful for things not related to TypeRep

**Comment by andrewthad** [comment]
The only thing I have in mind for this is a Map from `TypeRep a` to `f a`. I realized that there aren't any published libraries that do this.

**Comment by chessai** [comment]
What are you going to use that for

**Comment by chessai** [comment]
ping
